buildscript {
    repositories {
        mavenCentral()
    }
}

plugins {
    id 'java'
    alias(libs.plugins.springBoot) apply false
    alias(libs.plugins.springDependencyManagement) apply false
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

ext {
    springBootVersion = libs.versions.springBootVersion
}

allprojects {
    group = 'com.riftsmith'
    version = '0.0.1-SNAPSHOT'

    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'io.spring.dependency-management'

    group = 'com.riftsmith'
    version = '0.0.1-SNAPSHOT'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(25)
        }
    }

    dependencyManagement {
        imports {
            mavenBom("org.springframework.boot:spring-boot-dependencies:${springBootVersion}")
        }
    }

    dependencies {
        implementation libs.springBoot
        implementation libs.jakartaInjectApi
        implementation libs.jakartaPersistenceApi
        implementation libs.commonsMath3
        compileOnly libs.lombok
        annotationProcessor libs.lombok
        testImplementation libs.springBootStarterTest
        testImplementation libs.junitJupiterApi
        testRuntimeOnly libs.junitJupiterEngine
        testImplementation libs.junitPlatformLauncher
    }

   test {
        useJUnitPlatform()
    }
}