spring.application.name=riftbound-data-syncer
spring.datasource.url=jdbc:postgresql://db:5432/riftsmith
spring.datasource.username=riftsmith
spring.datasource.password=riftsmith

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true