description = 'infrastructure-riftbound'

dependencies {
    implementation project(':domain-riftbound')
    implementation project(':domain-data-fetch')

    implementation libs.springBootStarterDataJpa
    implementation libs.springBootStarterWeb

    runtimeOnly libs.postgresql
    implementation libs.flywayCore
    runtimeOnly libs.flywayPostgres

    compileOnly libs.lombok
    annotationProcessor libs.lombok
}